
export  const stakeTransactionActionTypes = {
    INIT_STAKETRANSACTIONS             :   'INIT_STAKETRANSACTIONS',
    SELECT_STAKETRANSACTION            :   'SELECT_STAKETRANSACTION',
    REMOVE_SELECTED_STAKETRANSACTION   :   'REMOVE_SELECTED_STAKETRANSACTION',
    DELETE_STAKETRANSACTION            :   'DELETE_STAKETRANSACTION',
    UPDATE_STAKETRANSACTION            :   'UPDATE_STAKETRANSACTION',
    INSERT_STAKETRANSACTION            :   'INSERT_STAKETRANSACTION'
}
