
export  const phasePercentPercentActionTypes = {
    INIT_PHASEPERCENTS             :   'INIT_PHASEPERCENTS',
    SELECT_PHASEPERCENT            :   'SELECT_PHASEPERCENT',
    REMOVE_SELECTED_PHASEPERCENT   :   'REMOVE_SELECTED_PHASEPERCENT',
    DELETE_PHASEPERCENT            :   'DELETE_PHASEPERCENT',
    UPDATE_PHASEPERCENT            :   'UPDATE_PHASEPERCENT',
    INSERT_PHASEPERCENT            :   'INSERT_PHASEPERCENT'
}
